include $(GOROOT)/src/Make.inc

TARG=MyBot
GOFILES=\
	ant.go\
	ants.go\
	direction.go\
	goal.go\
	item.go\
	location.go\
	main.go\
	MyBot.go\
	square.go\
	square_set.go\
	state.go\
	stats.go\
	timeout_loop.go\

include $(GOROOT)/src/Make.cmd
