include $(GOROOT)/src/Make.inc

TARG=MyBot
GOFILES=\
	ant.go\
	ants.go\
	direction.go\
	goal.go\
	item.go\
	location.go\
	main.go\
	MyBot.go\
	sqaure.go\
	state.go\
	stats.go\

include $(GOROOT)/src/Make.cmd
